/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesTetrisRouteImport } from './routes/games/tetris'
import { Route as Games2048RouteImport } from './routes/games/2048'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTetrisRoute = GamesTetrisRouteImport.update({
  id: '/games/tetris',
  path: '/games/tetris',
  getParentRoute: () => rootRouteImport,
} as any)
const Games2048Route = Games2048RouteImport.update({
  id: '/games/2048',
  path: '/games/2048',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/2048': typeof Games2048Route
  '/games/tetris': typeof GamesTetrisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/2048': typeof Games2048Route
  '/games/tetris': typeof GamesTetrisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/2048': typeof Games2048Route
  '/games/tetris': typeof GamesTetrisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/2048' | '/games/tetris'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/2048' | '/games/tetris'
  id: '__root__' | '/' | '/games/2048' | '/games/tetris'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Games2048Route: typeof Games2048Route
  GamesTetrisRoute: typeof GamesTetrisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/tetris': {
      id: '/games/tetris'
      path: '/games/tetris'
      fullPath: '/games/tetris'
      preLoaderRoute: typeof GamesTetrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/2048': {
      id: '/games/2048'
      path: '/games/2048'
      fullPath: '/games/2048'
      preLoaderRoute: typeof Games2048RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Games2048Route: Games2048Route,
  GamesTetrisRoute: GamesTetrisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
